name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with JFrog CLI
        run: |
          # Ping the server
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog rt c jerome-gcp --interactive=false --url=http://$ARTIFACTORY_HOSTNAME/artifactory --user=admin --apikey=$ARTIFACTORY_API_KEY
          ./jfrog rt ping
          ./jfrog rt gradle-config --server-id-resolve=jerome-gcp --server-id-deploy=jerome-gcp --repo-resolve=jerome-mvn-dev --repo-deploy=jerome-mvn-dev --use-wrapper=true
          ./jfrog rt gradle build artifactoryPublish -Dorg.gradle.daemon=false --build-name=pipelines-github-actions --build-number=42
          ./jfrog rt bp pipelines-github-actions $GITHUB_RUN_NUMBER
          ./jfrog rt bs pipelines-github-actions $GITHUB_RUN_NUMBER
